name: dimipay_kiosk
description: "Dimipay Kiosk"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_svg: ^2.0.9
  dimipay_design_kit: ^0.1.0
  material_symbols_icons: ^4.2716.0
  dio: ^5.4.0
  jwt_decode: ^0.3.1
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
  #   - asset/lottie/
  #   - asset/icon/

  fonts:
    - family: SUITv1
      fonts:
        - asset: assets/fonts/SUITv1-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUITv1-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUITv1-Light.ttf
          weight: 300
        - asset: assets/fonts/SUITv1-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUITv1-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUITv1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUITv1-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUITv1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUITv1-Heavy.ttf
          weight: 900