name: dimipay_pos_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  uuid: ^4.3.3
  jwt_decoder: ^2.0.1
  dimipay_design_kit: ^0.1.0
  material_symbols_icons: ^4.2716.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
  #   - asset/images/
  #   - asset/lottie/
  #   - asset/icon/

  fonts:
    - family: SUITv1
      fonts:
        - asset: assets/fonts/SUITv1-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUITv1-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUITv1-Light.ttf
          weight: 300
        - asset: assets/fonts/SUITv1-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUITv1-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUITv1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUITv1-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUITv1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUITv1-Heavy.ttf
          weight: 900