name: dimipay_pos_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # assets:
  #   - asset/images/
  #   - asset/lottie/
  #   - asset/icon/

  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat/Montserrat-Black.ttf
  #   - family: Pretendard
  #     fonts:
  #       - asset: fonts/Pretendard/Pretendard-Regular.ttf
  #         weight: 400
  #       - asset: fonts/Pretendard/Pretendard-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Pretendard/Pretendard-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Pretendard/Pretendard-Bold.ttf